apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-order-service
  labels:
    app: bookshop-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop-order-service
  template:
    metadata:
      labels:
        app: bookshop-order-service
    spec:
      containers:
        - name: bookshop-order-service
          image: bookshop-order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BOOKSHOP_BOOKSHOP_CATALOG_SERVICE_URI
              value: http://bookshop-catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://bookshop-config-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://bookshop-postgres/bookshopdb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://bookshop-postgres/bookshopdb_order
            - name : SPRING_RABBITMQ_HOST
              value: bookshop-rabbitmq
            - name : SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://bookshop-keycloak/realms/bookshop
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 15